openapi: 3.0.1
info:
  title: {{ cookiecutter['_@cortex_inputs']['service_details']['name'] }}
  x-cortex-tag: {{ cookiecutter['_@cortex_inputs']['service_details']['tag'] }}
  x-cortex-type: documentation
  x-cortex-definition: {}
  x-cortex-git:
    github:
      alias: {{ cookiecutter['_@cortex_inputs']['git']['repository']['alias']}}
      repository: {{ cookiecutter['_@cortex_inputs']['git']['repository']['org']}}/{{ cookiecutter['_@cortex_inputs']['git']['repository']['repoName'] }}
