openapi: 3.0.1
info:
  title: {{ cookiecutter['_@cortex_inputs']['service_details']['name'] }}
  x-cortex-tag: new-service
  x-cortex-groups:
  - tier-0
  x-cortex-owners:
  - type: EMAIL
    email: fernando.cremer@cortex.io
